[package]
authors = ["Aleh Zasypkin <aleh.zasypkin@gmail.com>"]
edition = "2018"
readme = "../README.md"
name = "kroneum-bin"
version = "0.1.0"
keywords = ["arm", "cortex-m"]
categories = ["embedded", "no-std"]
license = "MIT"
repository = "https://github.com/azasypkin/kroneum"

[dependencies]
cortex-m = "0.6.1"
cortex-m-rt = "0.6.10"
cortex-m-semihosting = "0.3.5"
kroneum-api = { version = "0.1.0", path = "../api" }
panic-semihosting = "0.5.2"
vcell = "0.1.2"

[dependencies.stm32f0]
version = "0.8.0"
features = ["stm32f0x2", "rt"]

[dev-dependencies.stm32f0xx-hal]
version = "0.15.1"
features = [ "rt", "stm32f042" ]

[dev-dependencies]
panic-halt = "0.2.0"
ssd1306 = "0.3.0-alpha.1"

[dev-dependencies.embedded-graphics]
version = "0.6.0-alpha.2"
features = ["bmp"]

# this lets you use `cargo fix`!
[[bin]]
name = "kroneum-bin"
test = false
bench = false

[features]
default = ["nightly"]
nightly = ["cortex-m/inline-asm", "cortex-m/const-fn"]