[package]
authors = ["Aleh Zasypkin <aleh.zasypkin@gmail.com>"]
edition = "2018"
readme = "../README.md"
name = "kroneum-bin"
version = "0.1.0"
keywords = ["arm", "cortex-m"]
categories = ["embedded", "no-std"]
license = "MIT"
repository = "https://github.com/azasypkin/kroneum"

[dependencies]
cortex-m = {version = "0.6.2", features = ["const-fn"]}
cortex-m-rt = "0.6.12"
kroneum-api = { version = "0.1.0", path = "../api" }
panic-reset = "0.1.0"
vcell = "0.1.2"
stm32f0xx-hal = {version = "0.16.0", features = ["stm32f042", "rt"]}

[dev-dependencies]
cortex-m-semihosting = "0.3.5"
ssd1306 = "0.3.0-alpha.2"
embedded-graphics = {version = "=0.6.0-alpha.2", features = ["bmp"]}

# this lets you use `cargo fix`!
[[bin]]
name = "kroneum-bin"
test = false
bench = false

[features]
nightly = ["cortex-m/inline-asm", "kroneum-api/nightly"]