[package]
authors = ["Aleh Zasypkin <aleh.zasypkin@gmail.com>"]
edition = "2018"
readme = "../README.md"
name = "kroneum-bin"
version = "0.1.0"
keywords = ["arm", "cortex-m"]
categories = ["embedded", "no-std"]
license = "MIT"
repository = "https://github.com/azasypkin/kroneum"

[dependencies]
cortex-m = "0.5.8"
cortex-m-rt = "0.6.8"
cortex-m-semihosting = "0.3.2"
kroneum-api = { version = "0.1.0", path = "../api" }
panic-semihosting = "0.5.1"
vcell = "0.1.0"

[dependencies.stm32f0]
version = "0.6.0"
features = ["stm32f0x2", "rt"]

# this lets you use `cargo fix`!
[[bin]]
name = "kroneum-bin"
test = false
bench = false

[features]
default = ["nightly"]
nightly = ["cortex-m/inline-asm", "cortex-m/const-fn"]