language: rust

rust:
- nightly

cache:
  directories:
  - "$HOME/.cargo"
  - "$TRAVIS_BUILD_DIR/target"

before_install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get update -qq; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install -y libusb-1.0-0 libusb-dev libhidapi-dev; fi

before_script:
  - rustup target add thumbv6m-none-eabi

script:
- cd sw/cli
- cargo build
- cd ../firmware
- cargo build --target thumbv6m-none-eabi --release
- cargo test

os:
- linux
- osx

notifications:
  email:
    on_success: never

branches:
  only:
  - master
