language: rust

rust:
- nightly

os:
  - linux
  - osx

cache:
  directories:
  - "$HOME/.cargo"
  - "$TRAVIS_BUILD_DIR/target"

addons:
  apt:
    packages:
      - build-essential
      - libudev-dev

before_install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then wget https://github.com/libusb/libusb/archive/v1.0.19.tar.gz -O libusb-1.0.19.tar.gz; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then tar -zxvf libusb-1.0.19.tar.gz; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then cd libusb-1.0.19 && ./autogen.sh && ./configure --prefix=$HOME/local && make && make install; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig pkg-config --list-all; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig pkg-config --libs libusb-1.0; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig pkg-config --modversion libusb-1.0; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then cd ..; fi

before_script:
  - rustup target add thumbv6m-none-eabi

script:
- cd sw/cli
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig LD_LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH cargo build; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then cargo build; fi
- cd ../firmware
- cargo build --target thumbv6m-none-eabi --release
- cargo test --package kroneum-api

notifications:
  email:
    on_success: never

branches:
  only:
  - master
