[package]
name = "kroneum-api"
version = "0.1.0"
authors = ["Aleh Zasypkin <aleh.zasypkin@gmail.com>"]
categories = ["embedded", "no-std"]

[dependencies]
bare-metal = "0.2.5"
bit_field = "0.10.0"
libm = "0.2.1"
vcell = "0.1.2"

[features]
nightly = []