[package]
name = "kroneum-api"
version = "0.1.0"
authors = ["Aleh Zasypkin <aleh.zasypkin@gmail.com>"]
categories = ["embedded", "no-std"]

[dependencies]
libm = "0.2.1"
vcell = "0.1.2"

[features]
nightly = []